<?php
/**
 * PreparedPaymentTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Stan
 * @author   Brightweb
 * @link     https://stan-business.fr
 */

/**
 * Stan API
 *
 * Stan Client API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Stan\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PreparedPaymentTest Class Doc Comment
 *
 * @category    Class
 * @description PreparedPayment
 * @package     Stan
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PreparedPaymentTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PreparedPayment"
     */
    public function testPreparedPayment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payment_id"
     */
    public function testPropertyPaymentId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "redirect_url"
     */
    public function testPropertyRedirectUrl()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
