<?php
/**
 * ApiSettingsTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Stan
 * @author Brightweb
 * @link https://stan-business.fr
 */

/**
 * Stan API
 *
 * Stan Client API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Stan\Test\Api;

use Stan\Api\ApiSettingsApi;
use Stan\Model\ApiSettingsRequestBody;

use Stan\Configuration;
use Stan\ApiException;
use Stan\ObjectSerializer;
use Stan\Api\StanClient;
use Stan\Test\Api\TestCase;

/**
 * ApiSettingsTest Class Doc Comment
 *
 * @category Class
 * @package  Stan
 * @author Brightweb
 * @link https://stan-business.fr
 */
class ApiSettingsTest extends TestCase
{

    /**
     * Test case for UpdateApiSettings
     *
     * Updates API settings.
     *
     */
    public function testUpdateApiSettings()
    {
        $this->client
            ->method('sendRequest')
            ->willReturn(null);

        $apiSettingsApi = new ApiSettingsApi($this->client);

        $this->assertSame(null, $apiSettingsApi->UpdateApiSettings(new ApiSettingsRequestBody()));
    }
}
