<?php
/**
 * ConnectApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Stan
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stan API
 *
 * Stan Client API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Stan\Test\Api;

use \Stan\Configuration;
use \Stan\ApiException;
use \Stan\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ConnectApiTest Class Doc Comment
 *
 * @category Class
 * @package  Stan
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConnectApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for userConnect
     *
     * Create an access token to request user's infos.
     *
     */
    public function testUserConnect()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
