<?php
/**
 * CustomerApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Stan
 * @author Brightweb
 * @link https://stan-business.fr
 */

/**
 * Stan API
 *
 * Stan Client API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Stan\Test\Api;

use Stan\Api\CustomerApi;
use Stan\Model\Customer;
use Stan\Model\CustomerRequestBody;

use Stan\Configuration;
use Stan\ApiException;
use Stan\ObjectSerializer;
use Stan\Api\StanClient;
use Stan\Test\Api\TestCase;

/**
 * CustomerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Stan
 * @author Brightweb
 * @link https://stan-business.fr
 */
class CustomerApiTest extends TestCase
{

    /**
     * Test case for create
     *
     * Create a new customer.
     *
     */
    public function testCreate()
    {
        $this->client
            ->method('sendRequest')
            ->willReturn('{"email": "stan@stan-app.fr"}');

        $customerApi = new CustomerApi($this->client);
        $customer = $customerApi->create(new CustomerRequestBody());

        $this->assertInstanceOf(Customer::class, $customer);
        $this->assertSame('stan@stan-app.fr', $customer->getEmail());
    }
}
