<?php
/**
 * UserApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Stan
 * @author Brightweb
 * @link https://stan-business.fr
 */

/**
 * Stan API
 *
 * Stan Client API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Stan\Test\Api;

use Stan\Api\UserApi;
use Stan\Model\User;

use Stan\Configuration;
use Stan\ApiException;
use Stan\ObjectSerializer;
use Stan\Api\StanClient;
use Stan\Test\Api\TestCase;

/**
 * UserApiTest Class Doc Comment
 *
 * @category Class
 * @package  Stan
 * @author Brightweb
 * @link https://stan-business.fr
 */
class UserApiTest extends TestCase
{

    /**
     * Test case for getUser
     *
     * Get user infos.
     *
     */
    public function testGetUser()
    {
        $this->client
            ->method('sendRequest')
            ->willReturn('{"sub": "sub_id"}');

        $user_api = new UserApi($this->client);
        $user = $user_api->getUser();

        $this->assertInstanceOf(User::class, $user);
        $this->assertSame('sub_id', $user->getSub());
    }
}
